// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhiNCaeMLOK5eRZE_O6WY23gHuIPnIV6s',
    appId: '1:78474404253:web:2b826bbbbf0fb09a970f74',
    messagingSenderId: '78474404253',
    projectId: 'simple-chat-d8861',
    authDomain: 'simple-chat-d8861.firebaseapp.com',
    storageBucket: 'simple-chat-d8861.firebasestorage.app',
    measurementId: 'G-ZGLP0C45CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLaQYzL-95lwfHfc4aMoT0z8LgSoePhmg',
    appId: '1:78474404253:android:9bcde7421345eadd970f74',
    messagingSenderId: '78474404253',
    projectId: 'simple-chat-d8861',
    storageBucket: 'simple-chat-d8861.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk3tGEsJhzQEMF8_hoF1g-YumjQBrTkZw',
    appId: '1:78474404253:ios:c15a196d92252964970f74',
    messagingSenderId: '78474404253',
    projectId: 'simple-chat-d8861',
    storageBucket: 'simple-chat-d8861.firebasestorage.app',
    iosBundleId: 'com.example.flutterMyChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk3tGEsJhzQEMF8_hoF1g-YumjQBrTkZw',
    appId: '1:78474404253:ios:c15a196d92252964970f74',
    messagingSenderId: '78474404253',
    projectId: 'simple-chat-d8861',
    storageBucket: 'simple-chat-d8861.firebasestorage.app',
    iosBundleId: 'com.example.flutterMyChatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhiNCaeMLOK5eRZE_O6WY23gHuIPnIV6s',
    appId: '1:78474404253:web:1272ce408cb06505970f74',
    messagingSenderId: '78474404253',
    projectId: 'simple-chat-d8861',
    authDomain: 'simple-chat-d8861.firebaseapp.com',
    storageBucket: 'simple-chat-d8861.firebasestorage.app',
    measurementId: 'G-EJ8V0ZE1GN',
  );
}
